# Generated by Django 3.0.8 on 2020-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='operation',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='calculator',
            name='value1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculator',
            name='value2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='output',
            field=models.IntegerField(default=0),
        ),
    ]
